version: '3.8'

services:
  admision_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admision_pro_app
    ports:
      - "7002:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - admision_db
    command: ["/entrypoint.sh"]
    networks:
      - nginx-proxy-manager_default

  admision_db:
    image: mysql:8.0
    container_name: admision_pro_db
    restart: always
    environment:
      MYSQL_DATABASE: bd_admision
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - admision_db_data:/var/lib/mysql
    networks:
      - nginx-proxy-manager_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admision_pro_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # ← Aquí estás exponiendo el puerto 8081 al exterior
    environment:
      PMA_HOST: admision_db
      PMA_PORT: 3306
    networks:
      - nginx-proxy-manager_default

volumes:
  admision_db_data:

networks:
  nginx-proxy-manager_default:
    external: true
